#!/bin/bash
# install_tracdev_env 

# TODO: use trac-trunk as default, use python-2.6 as default
install_dir=$1
trac_src=$2     #location of trac source code relative to this script
python=$3

install_dir_abs=`pwd`/$install_dir
genshi_src=genshi.git
tracdevplugin_src=tracdeveloperplugin/trunk
tracdevplugin_src_dir=$tracdevplugin_src
trac_src_dir=$trac_src
genshi_src_dir=$genshi_src

tracenv=tracdev  #name of Trac environment to create

#TODO: check if $installdir already exists and exit if yes

#TODO: add option to specify python version
echo Creating the virtualenv
virtualenv --system-site-packages --python=/usr/bin/python2.7 $install_dir
source $install_dir/bin/activate

# TODO: error check for available sources
echo Installing Trac and Genshi
cp -r $trac_src_dir $install_dir/
cp -r $genshi_src_dir $install_dir/
#cp -r $tracdevplugin_src_dir $install_dir/
cd $install_dir/$genshi_src_dir
python setup.py develop >&2
cd -
cd $install_dir/$trac_src_dir
python setup.py develop >&2
cd -

echo Creating the Trac environment
cd $install_dir
REPOS=`pwd`/repos/tracdev
trac-admin tracdev initenv TracDev sqlite:db/trac.db svn $REPOS >&2
trac-admin tracdev permission add anonymous TRAC_ADMIN >&2

echo Adding authentication information
htpasswd -bc $tracenv/.htpasswd user1 user1
htpasswd -b $tracenv/.htpasswd user2 user2
echo Creating user 'user1' with password 'user1'
echo Creating user 'user2' with password 'user2'
cd -

#echo Installing the TracDeveloperPlugin
#cd $tracdevplugin_src_dir
#python setup.py install >&2
#cd -

echo Creating the SVN repository
cd $install_dir
mkdir repos
svnadmin create repos/$tracenv
svn co file:///`pwd`/repos/$tracenv workingcopy
cd -

echo Change directories to $install_dir
echo Switch to the virtualenv using the command 'source bin/activate'
echo Start Trac with the command:
echo 'tracd -r -p 8000 --basic-auth="tracdev,`pwd`/tracdev/.htpasswd,TracDev Env" tracdev'
echo Navigate to http://localhost:8000/tracdev
