#!/bin/sh

bh_src=$2
mkdir "$1"
cp -R "$bh_src" "$1"/
cd "$1"

#svn co https://svn.apache.org/repos/asf/bloodhound/tags/0.5.3 bloodhound
#svn co https://svn.apache.org/repos/asf/bloodhound/trunk bloodhound
#git clone https://github.com/apache/bloodhound.git
virtualenv --python=python2.7 .
. bin/activate
cd "$bh_src"/installer
pip install -r requirements-dev.txt
#pip install -r requirements.txt

python bloodhound_setup.py --project=sqlite --database-type=sqlite --admin-user=admin --admin-password=admin

echo "tracd -r --port=8000 bloodhound/environments/sqlite"
